<a href="https://colab.research.google.com/github/igorvojnyak/datavojnyak.github.io/blob/master/Natural%20Language%20Processing%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
import matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.feature_extraction.text import  TfidfTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVC
from nltk.stem.porter import PorterStemmer
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
#from sklearn.impute import KNNImputer
from sklearn.svm import SVC
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import scipy.stats as st
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_selection import RFE
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from datetime import date, timedelta
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_squared_error
import numpy as np
from sklearn.metrics import confusion_matrix
import pandas as pd 
import pandas as pd
import warnings
from sklearn.feature_extraction.text import TfidfVectorizer
import tokenizer
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
from matplotlib.pyplot import rcParams
import matplotlib.pyplot as plt   
import seaborn as sns   
rcParams['figure.figsize'] = 16, 8
import json

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
df = pd.read_csv('/content/yelp.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   business_id  10000 non-null  object
 1   date         10000 non-null  object
 2   review_id    10000 non-null  object
 3   stars        10000 non-null  int64 
 4   text         10000 non-null  object
 5   type         10000 non-null  object
 6   user_id      10000 non-null  object
 7   cool         10000 non-null  int64 
 8   useful       10000 non-null  int64 
 9   funny        10000 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 781.4+ KB


In [4]:
df.columns

Index(['business_id', 'date', 'review_id', 'stars', 'text', 'type', 'user_id',
       'cool', 'useful', 'funny'],
      dtype='object')

In [5]:
df['stars'].unique()


array([5, 4, 2, 3, 1])

In [0]:
df['text_len'] = df['text'].apply(len)

In [0]:
#cleaning of text data
import re
def preprocessor(text):
    text = re.sub('<[^>]*>','', text)
    emoticons = re.findall('(7::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) + \
                  ' '.join(emoticons).replace('-','')
    return text                     

In [0]:
df['text'] = df['text'].apply(preprocessor)

In [9]:
df['text']

0       my wife took me here on my birthday for breakf...
1       i have no idea why some people give bad review...
2       love the gyro plate rice is so good and i also...
3       rosie dakota and i love chaparral dog park it ...
4       general manager scott petello is a good egg no...
                              ...                        
9995    first visit had lunch here today used my group...
9996    should be called house of deliciousness i coul...
9997    i recently visited olive and ivy for business ...
9998    my nephew just moved to scottsdale recently so...
9999    4 5 locations all 4 5 star average i think ari...
Name: text, Length: 10000, dtype: object

In [0]:
#word stemming, an algorithm for suffix strippng Porter
porter = PorterStemmer()
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [0]:
df['text'] = df['text'].apply(tokenizer_porter)

In [0]:
df['text']

0       [my, wife, took, me, here, on, my, birthday, f...
1       [i, have, no, idea, whi, some, peopl, give, ba...
2       [love, the, gyro, plate, rice, is, so, good, a...
3       [rosi, dakota, and, i, love, chaparr, dog, par...
4       [gener, manag, scott, petello, is, a, good, eg...
                              ...                        
9995    [first, visit, had, lunch, here, today, use, m...
9996    [should, be, call, hous, of, delici, i, could,...
9997    [i, recent, visit, oliv, and, ivi, for, busi, ...
9998    [my, nephew, just, move, to, scottsdal, recent...
9999    [4, 5, locat, all, 4, 5, star, averag, i, thin...
Name: text, Length: 10000, dtype: object

In [13]:
#dealing with stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.corpus import brown
import nltk
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [14]:
stop = set(stopwords.words('english')) 
df['text'].apply(lambda x: [item for item in x if item not in stop])

0       [wife, took, birthday, breakfast, wa, excel, w...
1       [idea, whi, peopl, give, bad, review, thi, pla...
2       [love, gyro, plate, rice, good, also, dig, can...
3       [rosi, dakota, love, chaparr, dog, park, veri,...
4       [gener, manag, scott, petello, good, egg, go, ...
                              ...                        
9995    [first, visit, lunch, today, use, groupon, ord...
9996    [call, hous, delici, could, go, thi, item, ite...
9997    [recent, visit, oliv, ivi, busi, last, week, 3...
9998    [nephew, move, scottsdal, recent, bunch, frien...
9999    [4, 5, locat, 4, 5, star, averag, think, arizo...
Name: text, Length: 10000, dtype: object

In [0]:
df['text']=[" ".join(review) for review in df['text'].values]

In [0]:
#Convert a collection of text documents to a matrix of token counts
class_ = df[(df.stars==1) | (df.stars==5)]
X = class_['text']
y = class_['stars']
cv = CountVectorizer()
X = cv.fit_transform(X)

In [20]:
print(cv.vocabulary_)

{'my': 7958, 'wife': 13127, 'took': 12163, 'me': 7487, 'here': 5714, 'on': 8382, 'birthday': 1487, 'for': 4738, 'breakfast': 1758, 'and': 747, 'it': 6354, 'wa': 12897, 'excel': 4267, 'the': 11950, 'weather': 13016, 'perfect': 8865, 'which': 13077, 'made': 7250, 'sit': 10789, 'outsid': 8521, 'overlook': 8552, 'their': 11956, 'ground': 5381, 'an': 735, 'absolut': 391, 'pleasur': 9101, 'our': 8494, 'waitress': 12924, 'food': 4717, 'arriv': 929, 'quickli': 9561, 'semi': 10502, 'busi': 1950, 'saturday': 10327, 'morn': 7844, 'look': 7116, 'like': 6995, 'place': 9062, 'fill': 4538, 'up': 12637, 'pretti': 9322, 'so': 10961, 'earlier': 3905, 'you': 13371, 'get': 5090, 'better': 1421, 'do': 3675, 'yourself': 13380, 'favor': 4442, 'bloodi': 1564, 'mari': 7365, 'phenomen': 8932, 'simpli': 10764, 'best': 1411, 've': 12740, 'ever': 4230, 'had': 5477, 'sure': 11587, 'they': 11979, 'onli': 8390, 'use': 12677, 'ingredi': 6192, 'from': 4884, 'garden': 5011, 'blend': 1546, 'them': 11958, 'fresh': 4844, '

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=101)

In [22]:
#MultinomialNB and create an instance of the estimator
nb = MultinomialNB()
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
#confusion matrix and classification report using these predictions and y_test 
predictions = nb.predict(X_test)
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[169  59]
 [ 32 966]]


              precision    recall  f1-score   support

           1       0.84      0.74      0.79       228
           5       0.94      0.97      0.96       998

    accuracy                           0.93      1226
   macro avg       0.89      0.85      0.87      1226
weighted avg       0.92      0.93      0.92      1226



In [0]:
#include TF-IDF to this process using a pipeline
tfidf = TfidfVectorizer(strip_accents=None,lowercase=False,preprocessor=None)

In [0]:
# pipeline with the following steps:CountVectorizer(), TfidfTransformer(),MultinomialNB()
pipeline = Pipeline([
                     ('bow', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('classifier', MultinomialNB()),

])

In [0]:
X = class_['text']
y = class_['stars']
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=101)

In [28]:
pipeline.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('bow',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [0]:
predictions = pipeline.predict(X_test)

In [30]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[  0 228]
 [  0 998]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       228
           5       0.81      1.00      0.90       998

    accuracy                           0.81      1226
   macro avg       0.41      0.50      0.45      1226
weighted avg       0.66      0.81      0.73      1226

